name = "sourav-image-api"        # Worker name
main = "index.js"                # <-- your worker JS file
account_id = "<YOUR_ACCOUNT_ID>" # Replace with your Cloudflare account ID
workers_dev = true
compatibility_date = "2026-03-08"
